### PR TITLE
Rename

### LINKED ISSUE #22: rename columns name using a (or several) Pair of Symbol or a Function (Symbol -> Symbol)
Hello,

A `rename!` function which rename several columns name using a Dict of Symbols or a column name using 2 Symbols (from_name, to_name) or a Pair of Symbol could probably be an interesting feature to have

See https://github.com/dysonance/Temporal.jl/issues/20#issuecomment-356232253

Kind regards

PS : 

Such a `rename!` function could be implemented like this:

```julia
function rename!(data::TS, d::Dict{Symbol, Symbol})
    flag = false
    for (i, field) in enumerate(data.fields)
        if field in keys(d)
            data.fields[i] = d[field]
            flag = true
        end
    end
    flag
end
```
`rename!` could also accept `Pair{Symbol, Symbol}` or 2 symbols as parameter

```julia
function rename!(data::TS, from_name::Symbol, to_name::Symbol)
    rename!(data, Dict(from_name=>to_name))
end

function rename!(data::TS, p::Pair{Symbol, Symbol})
    rename!(data, Dict(p))
end
```

### LINKED ISSUE #23: rename columns name using a function
Following https://github.com/dysonance/Temporal.jl/issues/20#issuecomment-363834526

A `rename!` function implementation could also accept a function as 2nd parameter which could rename column name in place.

Something like

```julia
rename!(data, c->replace(c, " ", ""))
```

Although TS column names are `Symbol`... not `String` so it will become

```julia
rename!(data, c->Symbol(replace(String(c), " ", "")))
```

but I'd prefer the Symbol/String complexity be hidden.

### PR DESCRIPTION
**Pull request by femtotrader**
Closes #22
Closes #23
Should help #20

### CODE REVIEW

**Comment by femtotrader** [comment]
odd codecov decrease!

**Comment by iblis17** [comment]
it's https://github.com/JuliaLang/julia/issues/28192

**Comment by dysonance** [comment]
Awesome, thanks for the contribution @femtotrader! It seems like the coverage issue linked by @iblis17 is something a lot of people are experiencing and the devs are aware of it and working on it, so I don't see that being a blocker to merge this. Thanks again for the help guys.

**Comment by femtotrader** [comment]
I think we should continue the discussion we started https://github.com/JuliaQuant/MarketTechnicals.jl/issues/93

**Pull request merged**
